// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLE8MXCi1Q4M_-yVmpwHXT1XR_QtwIKT4',
    appId: '1:666947467076:web:36f83ce4c097a427220911',
    messagingSenderId: '666947467076',
    projectId: 'nasa-space-apps-challeng-d0d02',
    authDomain: 'nasa-space-apps-challeng-d0d02.firebaseapp.com',
    storageBucket: 'nasa-space-apps-challeng-d0d02.appspot.com',
    measurementId: 'G-QSGGH00X5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaT0UIZTkCYvIkkcnyGUDzOF4Ed8tZcEc',
    appId: '1:666947467076:android:8072fccce56ccff0220911',
    messagingSenderId: '666947467076',
    projectId: 'nasa-space-apps-challeng-d0d02',
    storageBucket: 'nasa-space-apps-challeng-d0d02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE4_U03NmXLgQAFzzLo2mKcoTNf0Fhilg',
    appId: '1:666947467076:ios:7df4d426f1c801dc220911',
    messagingSenderId: '666947467076',
    projectId: 'nasa-space-apps-challeng-d0d02',
    storageBucket: 'nasa-space-apps-challeng-d0d02.appspot.com',
    iosBundleId: 'com.example.expeditoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE4_U03NmXLgQAFzzLo2mKcoTNf0Fhilg',
    appId: '1:666947467076:ios:7df4d426f1c801dc220911',
    messagingSenderId: '666947467076',
    projectId: 'nasa-space-apps-challeng-d0d02',
    storageBucket: 'nasa-space-apps-challeng-d0d02.appspot.com',
    iosBundleId: 'com.example.expeditoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLE8MXCi1Q4M_-yVmpwHXT1XR_QtwIKT4',
    appId: '1:666947467076:web:f31a270abe45d5b0220911',
    messagingSenderId: '666947467076',
    projectId: 'nasa-space-apps-challeng-d0d02',
    authDomain: 'nasa-space-apps-challeng-d0d02.firebaseapp.com',
    storageBucket: 'nasa-space-apps-challeng-d0d02.appspot.com',
    measurementId: 'G-YTD52KDR0K',
  );
}
